spring.application.name=chat_translate_demo

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/prizm_chat
spring.datasource.username=root
spring.datasource.password=1234
